### ISSUE TITLE
Detailed mode

### ISSUE THREAD

**Issue by liamcharmer** [bdrtsky/nuxt-ackee#7]
Having detailed mode turn on is great. However isn't it recommended by Ackee to ask for permission before activating it? Do we not need a cookie popup etc to accept which then enables detailed mode?

https://docs.ackee.electerious.com/#/docs/Privacy%20Policy

**Comment by lihbr** [comment]
Hey @liamcharmer, thanks for submitting an issue!

I'm not an expert so take my comment with a grain of salt but in regard to the GDPR, [data collected by Ackee](https://docs.ackee.electerious.com/#/docs/Anonymization#personal-data) cannot be considered as "personal data". However, Ackee has a stricter definition of what personal data are, therefore suggesting this best practice.

In the next major of this module (#5), there will be an option to easily let people opt-in/out this the detailed mode 🙂

Let me know if anything!

**Comment by liamcharmer** [comment]
Thank you so much! I should have checked! Sorry and thank you!!

**Comment by lihbr** [comment]
No worries! You're more than welcome :)
